[ballerina.log]
level = "INFO"

sourceSystem = "https://run.mocky.io/v3/1d9e8ba3-045c-42d9-a4d0-536d21d521af"


[ballerina.http.accessLogConfig]
# Enable printing access logs on the Console. The default value is `false`.
console = true